#deployment template
apiVersion: apps/V1
kind: Deployment
metadata:
  name: nginxdep
spec:
  # 1 Pod should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerport: 80