apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres
    app: postgres  # Adjust this to match the pod's labels
  ports:
    - port: 5432
      targetPort: 5432

