# Pod template multi fail concept
apiVersion: v1
kind: Pod
metadata:
  name: p1
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
  containers:
  - name: c2
    image: nginx
    ports:
    - containerPort: 80